services:
  cards:
    image: "vinay8493/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - "vinnybank"
  accounts:
    image: "vinay8493/accounts:s4"
    container_name: account-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - "vinnybank"
  loans:
    image: "vinay8493/loans:s4"
    container_name: loan-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - "vinnybank"
networks:
  vinnybank:
    driver: bridge
